# -*- coding: utf-8 -*-
"""yacctreeproduce.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16QfU5RZoMMDs2rYsRc6nm9XEu7kjGsOU
"""

from nltk import Tree
import datetime
input="('program' ('begin' 'T=C' 'C2/4' '|') ('statementlist' ('expression' ('music' 'NUMBER' 1) ('expression' ('music' 'BEAT' '_')  None))) ('END' '||'))"
t = Tree.fromstring(input)
t.pretty_print()